apiVersion: v1
kind: Service
metadata:
  name: namenode
spec:
  ports:
  - port: 50030
    name: jobracker
  - port: 8020
    name: hdfs
  - port: 22
    name: ssh
  clusterIP: None
  selector:
    app: namenode